services:
  app:
    build:
      context: .
      target: final
    image: anthonyargatoff/duckdns-updater
    # environment:
    #   - API_KEY=value
    #   - DOMAINE_NAME=value
    env_file: 
      - ./.env
    restart: always